add `store_picture` variable
Der-Henning/tgtg pull request #240
Opened 2023-01-14 15:07 UTC by p0lycarpio

Added the `store_picture` variable in the `item` model to be able to display the store logo in the notifications or webhooks.

2023-01-14 16:32 UTC, Der-Henning reviewed
Hi @p0lycarpio.
Thank you for your contribution.
I think we should add `store_cover` and `store_logo` as options.
And what about `item_cover` and `item_logo`? They seem to be the same as the store pictures. Or do you have an example where they differ?

Is `"-"` a reasonable default for an url?

2023-01-15 13:06 UTC, p0lycarpio commented
Hello @Der-Henning,
Indeed the `logo` and `cover` images look the same in `item` and `store`. I will take those of the item.

As for the default, the API seems to always return an image. For a store that does not have a logo, an image is generated with its initials. For the cover, there are several default values like : https://images.tgtg.ninja/standard_images/GENERAL/other1.jpg
What URL can I set for both images?

2023-01-25 18:47 UTC, Der-Henning requested changes
This looks fine. Please accept the changes to comply with the PEP8 style guide. Thank you.

2023-01-25 18:47 UTC, Der-Henning commented on src/models/item.py
> +            "current_url", "https://images.tgtg.ninja/standard_images/GENERAL/other1.jpg")
```suggestion
        self.item_logo = item.get("logo_picture", {}).get(
            "current_url",
            "https://tgtg-mkt-cms-prod.s3.eu-west-1.amazonaws.com/"
            "13512/TGTG_Icon_White_Cirle_1988x1988px_RGB.png")
        self.item_cover = item.get("cover_picture", {}).get(
            "current_url",
            "https://images.tgtg.ninja/standard_images/GENERAL/other1.jpg")
```
Fixing E501 line too long (> 79 characters)

2023-01-26 15:27 UTC, Der-Henning approved these changes

2023-01-26 15:28 UTC, merged